#Creating 0D Tensor or array


In [ ]:
import numpy as np
a = np.array(4)
a
a.ndim  #checking the dimension of tensor

array(4)

#Creating 1D Tensor

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print("dimension -> ",arr.ndim)

[1 2 3 4]
dimention ->  1


#Creating 2D Tensor | Matrices

In [ ]:
import numpy as np
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Dimension -> ",mat.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension ->  2


0